### PR TITLE
ADD: robots.txt to favicon app.get

### PR DESCRIPTION
**Pull request by Spazcool**
This seems to simple a change to be right for issue #35 
Is this correct?

### CODE REVIEW

**Comment by lenzai** [comment]
Well, it seems this code is returning status 503 rather than 204.
Something was already broken in that favicon code before you even started touching it.
@Spazcool

**Comment by Spazcool** [comment]
@lenzai I'm still uncertain on how to approach this and how it should behave. However, I did find one [comment](https://stackoverflow.com/questions/35408729/express-js-prevent-get-favicon-ico) that suggested the status function we were using was for an older version of express. 

I've changed to and committed the new syntax, locally the page no longer hangs and remains on whatever page the user had been on and I'm seeing no errors in the console.

**Comment by lenzai** [comment]
Check the http response status in browser network log or curl then we are
done.

**Comment by Spazcool** [comment]
Both favicon.ico and robots.txt return 204. Any others I need to add?

204response

**Pull request merged**
