### PR TITLE
Recent scans

### PR DESCRIPTION
**Pull request by Spazcool**
Recently scanned QR codes rendered to a page with human-readable time-stamp:

screenshot from 2017-11-19 22-19-50

### CODE REVIEW

**Comment by Spazcool** [comment]
So, do I hit the big green button "Merge pull request"?

**Comment by mpsido** [comment]
for me it is ok, but you can also wait for @lenzai 's review.
if you really need this code now, just go ahead

**Comment by Spazcool** [comment]
Nah, I'll wait.

**Comment by lenzai** [comment]
1. according to screenshot layout is breaking UUID on iphone. Change the layout so UUID displays on 1 full line.
2. make the existing items clickable or maybe reuse the search result layout? What do you think is best?
3. making the unassigned items clickable might be more convenient for testing after editing spreadsheet?
4. What happens if I edit spreadheet to assign uuid and refresh recent items ? Does it remain unassigned or change to "assigned" category ?
5. Change the titles unassigned => not found , assigned=> recent item.
.... or something like that. Focus on user perspective, not database/technical perspective.

**Comment by lenzai** [comment]
6. my machine still generates queries to robots.txt. Like as favicons, we should prevent those from being perceived as item uuid

**Comment by mpsido** [comment]
@lenzai you make good points but we could split this work in further commi.

**Comment by Spazcool** [comment]
@lenzai comments & questions:
2 & 3. You want the items clickable to what? Linked to the search page, item page, spreadsheet? 
4. After being assigned on the spreadsheet, and scanned once again, the item will appear in both lists simultaneously. Is this behaviour you want changed? 
6. I don't understand the issue. Is it what we've been going on about on WeChat?

**Comment by lenzai** [comment]
@Spazcool 
6.
http://url.coderbunker.com/robots.txt should not appear in recent scanned, same as favicon.ico.

2.3. click to equipment page. After editing the spreadsheet seems natural to check how it looks like on the website.

4. My concern is how to determine if a missing UUID has been fixed in the spreadsheet has been solved or not. Current behavior does not make it easy. I am not sure what could be a good solution in order to minimise code complexity.

**Comment by Spazcool** [comment]
@lenzai  
4. So, if a UUID is already in one list, remove it before adding it into the other.
6. Ok. Got it.

**Comment by lenzai** [comment]
4. seems like a brutal shortcut, deleting multiple entries in the history. 
Let's leave it for now and see if users complain after launching.

**Comment by lenzai** [comment]
1.2.3.5 completed by Qiong
4. canceled

**Pull request merged**
